config/routes.rb
Rails.application.routes.draw do
  scope :search do
    get 'authors(/:query)', as: 'author_search', action: 'author_search', controller: 'authors'
    get 'publishers(/:query)', as: 'publisher_search', action: 'publisher_search', controller: 'publishers'
  end
  resources :books
  resources :publishers
  resources :authors 
  


  namespace :statistics do
    get 'books/created', as: 'created_books', action: 'created_books'
    get 'books/authors', as: 'books_by_authors', action: 'books_by_authors'
    get 'books/publishers', as: 'books_by_publishers', action: 'books_by_publishers'
  end
  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, inverse_of: :author
  has_many :publishers, through: :books, inverse_of: :authors
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html
      format.json {render json: @authors.map { |e| {name: e.full_name} }}
    end
  end

  def author_search
    if params[:query]
      @authors = Author.where("LOWER(authors.full_name) LIKE :query", {query:  "%#{params[:query].downcase}%"})
    else
      @authors = Author.all
    end
    render json: {data: {query: params[:query], count: @authors.count, results: @authors.map {|a| {name: a.full_name}}}}
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to authors_path, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to authors_path, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:full_name, :display_name)
    end
end

app/views/authors/_author_fields.html.erb
<div class="row">
  <div class="col-md-12">
    <%= f.input :full_name %>
  </div>
  <div class="col-md-12">
    <%= f.input :display_name %>
  </div>
</div>

app/views/authors/_form.html.erb
<%= simple_form_for @author do |f| %>
<div class="card-body">
  <%= render "authors/author_fields", f: f %>
</div>
<div class="card-footer text-right">
  <hr>
  <%= link_to 'Back', :back, class: "btn btn-secondary" %>
  <%= f.button :submit, class: "btn btn-primary" %>
</div>
<% end -%>

app/views/authors/edit.html.erb
<%= render 'layouts/header_sm' %>
<div class="content">
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h5 class="title">Editing Author</h5>
        </div>      
        <%= render 'form', author: @author %>
      </div>
    </div>
  </div>
</div>

app/views/authors/index.html.erb
<%= render 'layouts/header_sm' %>
<div class="content">
  <div class="row">
    <div class="col-md-6">
      <div class="card card-tasks">
        <div class="card-header">
          <h5 class="card-category">Authors</h5>
          <h4 class="card-title">Every Author</h4>
        </div>
        <div class="card-body">
          <div class="table-full-width table-responsive">
            <table class="table">
              <tbody>
                <% @authors.each do |author| %>
                <tr>  
                  <td>
                    <%= button_to author, class: "btn btn-info btn-round btn-icon btn-icon-mini btn-neutral", html_options: {rel: "tooltip", title: ""}, method: :get, data: {"original-title": "Show Author"} do %>
                      <%= fa_icon 'eye 2x' %>
                    <% end %>
                  </td>
                  <td class="text-left">
                    <strong><%= author.full_name %></strong>
                    <small></small>
                  </td>
                  <td class="td-actions text-right">
                    <%= button_to edit_author_path(author), class: "btn btn-info btn-round btn-icon btn-icon-mini btn-neutral", html_options: {rel: "tooltip", title: ""}, method: :get, data: {"original-title": "Edit Author"} do %>
                      <%= fa_icon 'edit 2x' %>
                    <% end %>
                    <%= button_to author, class: "btn btn-danger btn-round btn-icon btn-icon-mini btn-neutral", html_options: {rel: "tooltip", title: ""}, method: :delete, data: { confirm: 'Are you sure?', "original-title": "Remove"} do %>
                      <%= fa_icon 'trash 2x' %>
                    <% end %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer">
          <hr>          
          <div class="stats">
            <%= link_to 'New Author', new_author_path %>  
            <!-- <i class="now-ui-icons loader_refresh spin"></i> Updated 3 minutes ago -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/authors/new.html.erb
<%= render 'layouts/header_sm' %>
<div class="content">
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h5 class="title">New Author</h5>
        </div>
          <%= render 'form', author: @author %>
      </div>
    </div>
  </div>
</div>

app/views/authors/show.html.erb
<%= render 'layouts/header_sm' %>
<div class="content">
  <div class="row">
    <div class="col-md-4">
      <div class="card">
        <%= image_tag 'unknown.jpg', class: "card-img-top", alt: "unknown" %>
        <div class="card-body">
          <h5 class="title"><%= @author.full_name %></h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            ISBN: <%#= @author.isbn %>
          </li>
          <li class="list-group-item">
            Autor: <%#= link_to @author.author do %>
            <%#= @author.author.full_name %>
            <%# end -%>
          </li>
          <li class="list-group-item">
            Verlag: Heine<%#= @author.publisher %>
          </li>
          <li class="list-group-item">
            Release: 2018<%#= @author.release %>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-md-1"></div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-header text-center">
          <h5>Books from <%=@author.full_name%></h5>
        </div>
        <div class="card-body">
          <div class="list-group">
            <% @author.books.each do |book| %>
            <%= link_to book, class: "list-group-item list-group-item-action flex-column align-items-start" do %>
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1"><%= book.title %></h5>
              <small>Heine (2018)</small>
            </div>
            <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
            <small><%= book.isbn %></small>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>