config/routes.rb
Rails.application.routes.draw do
  scope :search do
    get 'authors(/:query)', as: 'author_search', action: 'author_search', controller: 'authors'
    get 'publishers(/:query)', as: 'publisher_search', action: 'publisher_search', controller: 'publishers'
  end
  resources :books
  resources :publishers
  resources :authors 
  


  namespace :statistics do
    get 'books/created', as: 'created_books', action: 'created_books'
    get 'books/authors', as: 'books_by_authors', action: 'books_by_authors'
    get 'books/publishers', as: 'books_by_publishers', action: 'books_by_publishers'
  end
  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books, inverse_of: :author
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, only: [:show, :edit, :update, :destroy]

  # GET /publishers
  # GET /publishers.json
  def index
    @publishers = Publisher.all
  end

  def publisher_search
    if params[:query]
      @publishers = Publisher.where("LOWER(publishers.name) LIKE :query", {query: "%#{params[:query].downcase}%"})
    else
      @publishers = Publisher.all
    end
    render json: {data: {query: params[:query], count: @publishers.count, results: @publishers.map {|a| {name: a.name}}}}
  end

  # GET /publishers/1
  # GET /publishers/1.json
  def show
  end

  # GET /publishers/new
  def new
    @publisher = Publisher.new
  end

  # GET /publishers/1/edit
  def edit
  end

  # POST /publishers
  # POST /publishers.json
  def create
    @publisher = Publisher.new(publisher_params)

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to publishers_path, notice: 'Publisher was successfully created.' }
        format.json { render :show, status: :created, location: @publisher }
      else
        format.html { render :new }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publishers/1
  # PATCH/PUT /publishers/1.json
  def update
    respond_to do |format|
      if @publisher.update(publisher_params)
        format.html { redirect_to publishers_path, notice: 'Publisher was successfully updated.' }
        format.json { render :show, status: :ok, location: @publisher }
      else
        format.html { render :edit }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishers/1
  # DELETE /publishers/1.json
  def destroy
    @publisher.destroy
    respond_to do |format|
      format.html { redirect_to publishers_url, notice: 'Publisher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publisher_params
      params.require(:publisher).permit(:name)
    end
end

app/views/publishers/_form.html.erb
<%= simple_form_for @publisher do |f| %>
<div class="card-body">
  <%= render "publishers/publisher_fields", f: f %>
</div>
<div class="card-footer text-right">
  <hr>
  <%= link_to 'Back', :back, class: "btn btn-secondary" %>
  <%= f.button :submit, class: "btn btn-primary" %>
</div>
<% end -%>

app/views/publishers/_publisher_fields.html.erb
<div class="row">
  <div class="col-md-12">
    <%= f.input :name %>
  </div>
  
</div>

app/views/publishers/edit.html.erb
<%= render 'layouts/header_sm' %>
<div class="content">
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h5 class="title">Editing Publisher</h5>
        </div>
          <%= render 'form', publisher: @publisher %>
      </div>
    </div>
  </div>
</div>

app/views/publishers/index.html.erb
<%= render 'layouts/header_sm' %>
<div class="content">
  <div class="row">
    <div class="col-md-6">
      <div class="card card-tasks">
        <div class="card-header">
          <h5 class="card-category">Publishers</h5>
          <h4 class="card-title">Every Publisher</h4>
        </div>
        <div class="card-body">
          <div class="table-full-width table-responsive">
            <table class="table">
              <tbody>
                <% @publishers.each do |publisher| %>
                <tr>  
                  <td>
                    <%= button_to publisher, class: "btn btn-info btn-round btn-icon btn-icon-mini btn-neutral", html_options: {rel: "tooltip", title: ""}, method: :get, data: {"original-title": "Show Publisher"} do %>
                      <%= fa_icon 'eye 2x' %>
                    <% end %>
                  </td>
                  <td class="text-left">
                    <strong><%= publisher.name %></strong>
                    <small></small>
                  </td>
                  <td class="td-actions text-right">
                    <%= button_to edit_publisher_path(publisher), class: "btn btn-info btn-round btn-icon btn-icon-mini btn-neutral", html_options: {rel: "tooltip", title: ""}, method: :get, data: {"original-title": "Edit Publisher"} do %>
                      <%= fa_icon 'edit 2x' %>
                    <% end %>
                    <%= button_to publisher, class: "btn btn-danger btn-round btn-icon btn-icon-mini btn-neutral", html_options: {rel: "tooltip", title: ""}, method: :delete, data: { confirm: 'Are you sure?', "original-title": "Remove"} do %>
                      <%= fa_icon 'trash 2x' %>
                    <% end %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer">
          <hr>          
          <div class="stats">
            <%= link_to 'New Publisher', new_publisher_path %>  
            <!-- <i class="now-ui-icons loader_refresh spin"></i> Updated 3 minutes ago -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/publishers/new.html.erb
<%= render 'layouts/header_sm' %>
<div class="content">
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h5 class="title">New Publisher</h5>
        </div>
          <%= render 'form', publisher: @publisher %>
      </div>
    </div>
  </div>
</div>

app/views/publishers/show.html.erb
<%= render 'layouts/header_sm' %>
<div class="content">
  <div class="row">
    <div class="col-md-4">
      <div class="card">
        <%= image_tag 'unknown.jpg', class: "card-img-top", alt: "unknown" %>
        <div class="card-body">
          <h5 class="title"><%= @publisher.name %></h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            ISBN: <%#= @publisher.isbn %>
          </li>
          <li class="list-group-item">
            Autor: <%#= link_to @publisher.publisher do %>
            <%#= @publisher.publisher.name %>
            <%# end -%>
          </li>
          <li class="list-group-item">
            Verlag: Heine<%#= @publisher.publisher %>
          </li>
          <li class="list-group-item">
            Release: 2018<%#= @publisher.release %>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-md-1"></div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-header text-center">
          <h5>Books from <%=@publisher.name%></h5>
        </div>
        <div class="card-body">
          <div class="list-group">
            <% @publisher.books.each do |book| %>
            <%= link_to book, class: "list-group-item list-group-item-action flex-column align-items-start" do %>
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1"><%= book.title %></h5>
              <small>Heine (2018)</small>
            </div>
            <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
            <small><%= book.isbn %></small>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>