config/routes.rb
Rails.application.routes.draw do
  scope :search do
    get 'authors(/:query)', as: 'author_search', action: 'author_search', controller: 'authors'
    get 'publishers(/:query)', as: 'publisher_search', action: 'publisher_search', controller: 'publishers'
  end
  resources :books
  resources :publishers
  resources :authors 
  


  namespace :statistics do
    get 'books/created', as: 'created_books', action: 'created_books'
    get 'books/authors', as: 'books_by_authors', action: 'books_by_authors'
    get 'books/publishers', as: 'books_by_publishers', action: 'books_by_publishers'
  end
  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author, inverse_of: :books
  belongs_to :publisher, inverse_of: :books

  accepts_nested_attributes_for :author, reject_if: :all_blank?
  accepts_nested_attributes_for :publisher, reject_if: :all_blank?
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show,:edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.eager_load(:author, :publisher).all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    @book.build_author
    @book.build_publisher
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    author = Author.where(book_params[:author_attributes]).first_or_create(full_name: book_params[:author_attributes][:full_name], display_name: book_params[:author_attributes][:full_name])
    publisher = Publisher.where(book_params[:publisher_attributes]).first_or_create
    @book = Book.where(title: book_params[:title], isbn: book_params[:isbn], author: author, publisher: publisher).first_or_initialize

    respond_to do |format|
      if @book.save
        format.html { redirect_to books_path, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    author = Author.where(full_name: book_params[:author_attributes][:full_name]).first_or_create(full_name: book_params[:author_attributes][:full_name], display_name: book_params[:author_attributes][:full_name])
    publisher = Publisher.where(name: book_params[:publisher_attributes][:name]).first_or_create
    
    respond_to do |format|
      if @book.update(title: book_params[:title], isbn: book_params[:isbn], author: author, publisher: publisher)
        format.html { redirect_to books_path, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :isbn, author_attributes: [:id, :full_name], publisher_attributes: [:id, :name])
    end
  end

app/views/books/_book_fields.html.erb
<div class="row">
  <div class="col-md-7">
    <%= f.input :title, label: "Title", placeholder: "e.g. My very first Book" %>
  </div>
  <div class="col-md-5">
    <%= f.input :isbn, label: "ISBN", placeholder: "e.g. 9783161484100" %>
  </div>
</div>

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
<div class="card-body">
  <%= render "books/book_fields", f: f %>
  <%= f.simple_fields_for :author do |author| %>
    <div class="row">
      <div class="col-md-12">
        <%= author.input :full_name, label: "Author", placeholder: "e.g. J. K. Rowling",required: true, input_html: {class: "author typeahead"} %>
      </div>
    </div>
  <% end -%>
  <%= f.simple_fields_for :publisher do |publisher| %>
    <div class="row">
      <div class="col-md-12">
        <%= publisher.input :name, label: "Publisher", placeholder: "e.g. Rheinwerk Verlag",required: true, input_html: {class: "publisher typeahead"} %>
      </div>
    </div>
  <% end -%>
</div>
<div class="card-footer text-right">
  <hr>
  <%= link_to 'Back', :back, class: "btn btn-secondary" %>
  <%= f.button :submit, class: "btn btn-primary" %>
</div>
<% end -%>

app/views/books/edit.html.erb
<%= render 'layouts/header_sm' %>
<div class="content">
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h5 class="title">Editing Book</h5>
        </div>
          <%= render 'form', book: @book %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/header_sm' %>
<div class="content">
  <div class="row">
    <div class="col-md-6">
      <div class="card card-books">
        <div class="card-header">
          <h5 class="card-category">Books</h5>
          <h4 class="card-title">Your Books</h4>
        </div>
        <div class="card-body">
          <div class="table-full-width table-responsive">
            <table class="table">
              <tbody>
                <% @books.each do |book| %>
                <tr>
                  <td>
                    <div class="row">
                      <div class="col-md-3">
                        <%= link_to book do %>
                          <%= image_tag 'unknown_cover.jpg', alt: "No Cover" %>
                        <% end -%>
                      </div>
                      <div class="col-md-5">
                        <h5><strong><%= book.title %></strong></h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.<%#= book.description %></p>
                        <small><%= "(2018,#{link_to book.author.display_name ,book.author}, #{link_to book.publisher.name, book.publisher}, ISBN: #{book.isbn})".html_safe %></small>
                      </div>
                    </div>
                  </td>
                  <td class="td-actions text-right">
                    <%= button_to edit_book_path(book), class: "btn btn-info btn-round btn-icon btn-icon-mini btn-neutral", html_options: {rel: "tooltip", title: ""}, method: :get, data: {"original-title": "Edit Book"} do %>
                    <%= fa_icon 'edit 2x' %>
                    <% end %>
                    <%= button_to book, class: "btn btn-danger btn-round btn-icon btn-icon-mini btn-neutral", html_options: {rel: "tooltip", title: ""}, method: :delete, data: { confirm: 'Are you sure?', "original-title": "Remove"} do %>
                    <%= fa_icon 'trash 2x' %>
                    <% end %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer">
          <hr>          
          <div class="stats">
            <%= link_to 'New Book', new_book_path %>  
            <!-- <i class="now-ui-icons loader_refresh spin"></i> Updated 3 minutes ago -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<%= render 'layouts/header_sm' %>
<div class="content">
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h5 class="title">New Book</h5>
        </div>
          <%= render 'form', book: @book %>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= render 'layouts/header_sm' %>
<div class="content">
  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <%= image_tag 'unknown_cover.jpg', class: "card-img-top", alt: "unknown" %>
        <div class="card-body">
          <h5 class="title"><%= @book.title %></h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            ISBN: <%= @book.isbn %>
          </li>
          <li class="list-group-item">
            Autor: <%= link_to @book.author do %>
              <%= @book.author.full_name %>
            <% end -%>
          </li>
          <li class="list-group-item">
            Verlag: Heine<%#= @book.publisher %>
          </li>
          <li class="list-group-item">
            Release: 2018<%#= @book.release %>
          </li>
        </ul>
        <!-- <div class="card-body">
          <a href="#" class="card-link">Card link</a>
          <a href="#" class="card-link">Another link</a>
        </div> -->
      </div>
    </div>
    <div class="col-md-5">
      <div class="card">
        
        <div class="card-body">
          <div class="list-group">
  <a href="#" class="list-group-item list-group-item-action flex-column align-items-start active">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">List group item heading</h5>
      <small>3 days ago</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small>Donec id elit non mi porta.</small>
  </a>
  <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">List group item heading</h5>
      <small class="text-muted">3 days ago</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small class="text-muted">Donec id elit non mi porta.</small>
  </a>
  <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">List group item heading</h5>
      <small class="text-muted">3 days ago</small>
    </div>
    <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
    <small class="text-muted">Donec id elit non mi porta.</small>
  </a>
</div>
        </div>
      </div>
    </div>
  </div>
</div>