config/routes.rb
Rails.application.routes.draw do
  scope :search do
    get 'authors(/:query)', as: 'author_search', action: 'author_search', controller: 'authors'
    get 'publishers(/:query)', as: 'publisher_search', action: 'publisher_search', controller: 'publishers'
  end
  resources :books
  resources :publishers
  resources :authors 
  


  namespace :statistics do
    get 'books/created', as: 'created_books', action: 'created_books'
    get 'books/authors', as: 'books_by_authors', action: 'books_by_authors'
    get 'books/publishers', as: 'books_by_publishers', action: 'books_by_publishers'
  end
  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_fixed_setting.html.erb
<div class="fixed-plugin">
  <div class="dropdown show-dropdown">
    <a href="#" data-toggle="dropdown" aria-expanded="false">
      <%= fa_icon 'cog 2x'%>
    </a>
    <ul class="dropdown-menu" x-placement="top-start" style="position: absolute; transform: translate3d(-231px, -346px, 0px); top: 0px; left: 0px; will-change: transform;">
      <li class="header-title"> Sidebar Background</li>
      <li class="adjustments-line">
        <a class="switch-trigger background-color">
          <div class="badge-colors text-center">
            <span class="badge filter badge-yellow" data-color="yellow"></span>
            <span class="badge filter badge-blue" data-color="blue"></span>
            <span class="badge filter badge-green" data-color="green"></span>
            <span class="badge filter badge-orange active" data-color="orange"></span>
            <span class="badge filter badge-red" data-color="red"></span>
          </div>
          <div class="clearfix"></div>
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
    <nav>
      <ul>
        <li>
          <%= link_to "Privacy",root_path %>
        </li>
        <li>
          <%= link_to "About",root_path %>
        </li>
        <li>
          <%= link_to "Impressum",root_path %>
        </li>
        <li>
          <%= link_to '#', class: "nav-link" do %>
          <%= fa_icon 'arrow-up', text: "Top" %>
          <p>
            <span class="d-lg-none d-md-block">Top</span>
          </p>
          <% end %>
        </li>
      </ul>
    </nav>
    <div class="copyright">
      &copy;
      <%= Date.today.year %>
      Max 
    </div>
  </div>
</footer>

app/views/layouts/_header_sm.html.erb
<div class="panel-header panel-header-sm"></div>

app/views/layouts/_navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute bg-primary fixed-top">
  <div class="container-fluid">
    <div class="navbar-wrapper">
      <div class="navbar-toggle">
        <button type="button" class="navbar-toggler">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </button>
      </div>
      <%= link_to 'Lesekiste', root_path, class: "navbar-brand" %>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-bar navbar-kebab"></span>
      <span class="navbar-toggler-bar navbar-kebab"></span>
      <span class="navbar-toggler-bar navbar-kebab"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navigation">
      <ul class="navbar-nav">
        <% if !current_page?(root_path) %>
          <li class="nav-item">
            <%= link_to :back, class: "nav-link" do %>
            <%= fa_icon 'arrow-left', text: "Back" %>
            <p>
              <span class="d-lg-none d-md-block">Back</span>
            </p>
            <% end %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= fa_icon 'user' %>
            <p>
              <span class="d-lg-none d-md-block">Account</span>
            </p>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <a class="dropdown-item" href="#">Logout</a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="sidebar" data-color="orange">
  <div class="logo">
    <%= link_to 'LK', root_path, class: "simple-text logo-mini" %>
    <%= link_to 'Lesekiste', root_path, class: "simple-text logo-normal" %>
  </div>
  <div class="sidebar-wrapper">
    <ul class="nav">
      <li class="<%= "active" if current_page?(root_path)%>">
        <%= link_to root_path do %>
          <%= fa_icon 'home' %>
          <p>Overview</p>
        <% end -%>
      </li>
      <li class="<%= "active" if current_page?(books_path)%>">
        <%= link_to books_path do %>
          <%= fa_icon 'book' %>
          <p>Books</p>
        <% end -%>
      </li>
      <li class="<%= "active" if current_page?(authors_path)%>">
        <%= link_to authors_path do %>
          <%= fa_icon 'users' %>
          <p>Authors</p>
        <% end -%>
      </li>
      <li class="<%= "active" if current_page?(publishers_path)%>">
        <%= link_to publishers_path do %>
          <%= fa_icon 'building' %>
          <p>Publishers</p>
        <% end -%>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="/images/apple-icon.png">
  <link rel="icon" type="image/png" href="/images/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>Lesekiste</title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="">
  <div class="wrapper ">
    <%= render 'layouts/sidebar' %>
    <div class="main-panel">
      <%= render 'layouts/navbar' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%#= render 'layouts/fixed_setting' %>
    </div>
  </div>

</body>

</html>